soundeed/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path("register/", views.register_request, name="register"),
    path("login/", views.login_request, name="login"),
    path("logout/", views.logout_request, name= "logout"),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path("iwannaseeerror/", views.error404, name="error404"),
    path("password_change/", views.password_change, name="password_change")
]

soundeed/soundeed/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url, handler404, handler500
from django.views.static import serve 

handler404 = "main.views.error404"
handler500 = "main.views.error500"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    url(r'^login/', include('main.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="user/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'), name='password_reset_complete'),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

soundeed/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE


# Create your models here.
class Sound(models.Model):
    title = models.TextField(max_length=50, default="Sound")
    date = models.DateField(auto_now=False, auto_now_add=True)
    avatar = models.ImageField(upload_to='avatar', default='default.png', blank=True)
    icon = models.CharField("Bootstrap Icon", max_length=50, blank=True)
    audio = models.FileField(upload_to='audio', default='default.mp3')
    natural = "natural"
    social = "social"
    category = models.CharField(
        max_length=50,
        choices = (
            (natural, natural),
            (social, social)
        )
    )
    
    def __str__(self):
        return self.title
    
class Background(models.Model):
    title = models.TextField(max_length=50, default="Background")
    date = models.DateField(auto_now=False, auto_now_add=True)
    thumbnail = models.ImageField(upload_to='thumbnail', default='default.png', blank=True)
    background = models.FileField(upload_to='background', default='default.png')
    static = "static"
    dynamic = "dynamic"
    category = models.CharField(
        max_length=50,
        choices = (
            (static, static),
            (dynamic, dynamic)
        )
    )
    
    def __str__(self):
        return str(self.background)

class PlayList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.TextField(max_length=50, default="Playlist")
    playlist = models.CharField(max_length=100, default="Playlist")

    def __str__(self):
        return str(self.title)

soundeed/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Field

class NewUserForm(UserCreationForm):
	username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','type':'text','name': 'username','placeholder':'Username'}),label="Username")
	email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control','type':'text','name': 'email','placeholder':'Email'}), label="Email")
	password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','type':'password', 'name':'password1', 'placeholder':'Password'}),label="Password")
	password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','type':'password', 'name': 'password2', 'placeholder':'Password again'}),label="Password again")

	class Meta:
		model = User
		fields = ['username', 'email','password1','password2']
		field_order = ['email','password1','password2']
	
	def __init__(self, *args, **kwargs):
		super(NewUserForm, self).__init__(*args, **kwargs)
		helper = self.helper = FormHelper()
		self.helper.layout = Layout(
            Fieldset(
                'username',
                'email',
                'password1',
                'password2',
            ),
            ButtonHolder(
                Submit('submit', 'Submit', css_class='button white')
            )
        )
		# Moving field labels into placeholders
		layout = helper.layout = Layout()
		for field_name, field in self.fields.items():
			layout.append(Field(field_name, placeholder=field.label))
		helper.form_show_labels = False

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

soundeed/main/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm
from django.contrib.auth import login, authenticate, logout, update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm, PasswordChangeForm
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.contrib.auth.models import User
from django.core.mail import BadHeaderError, send_mail
from .models import Sound, Background, PlayList


# Create your views here.
def index(response):
    if response.method == "POST":
        if response.POST.get("new"):
            txt = response.POST.get("new")
            txtPlayList = response.POST.get("addPlayList")

        new_list = PlayList(user=response.user, title=txt, playlist=txtPlayList)
        new_list.save()
        return redirect("/")

    return render(
        response,
        "pages/index.html",
        {"sound": Sound.objects.all(), "background": Background.objects.all()},
    )


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("/")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request, "user/register.html", context={"register_form": form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                if user.is_superuser:
                    return redirect("/admin")
                else:
                    return redirect("/")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request, "user/login.html", context={"login_form": form})


def logout_request(request):
    logout(request)
    messages.info(request, f"You have successfully logged out.")
    return redirect("/")


# PASSWORD EMAIL REQUEST
def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data["email"]
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "user/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        "domain": "127.0.0.1:8000",
                        "site_name": "SOUNDeeD",
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        "token": default_token_generator.make_token(user),
                        "protocol": "http",
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(
                            subject, email, "admin@soundeed.com", [user.email], fail_silently=False
                        )
                    except BadHeaderError:
                        return HttpResponse("Invalid header found.")
                    return redirect("password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(
        request=request,
        template_name="user/password_reset.html",
        context={"password_reset_form": password_reset_form},
    )


def password_change(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, "Your password was successfully updated!")
            return redirect("/")
        else:
            messages.error(request, "Please correct the error below.")
    else:
        form = PasswordChangeForm(request.user)
    return render(request, "user/password_change.html", {"form": form})


def error404(request, exception):
    return render(request, "pages/error.html", {"message": "hello"})


def error500(request):
    return render(request, "pages/error.html")

soundeed/main/templates/pages/about.html
<div id="about-con" class="d-none">
    <div class="container no-select">
        <a href="#about" class="text-decoration-none">
            <h2 class="text-center mx-auto py-4" style="font-size: 35px; line-height: 50px;">ABOUT <b>SOUNDeeD</b></h2>
        </a>
        <div class="px-3">
            <p> <b>SOUNDeeD</b> is a website which is designed to help you relax, focus with your work, study,....
            </p>
            <p>

            </p>
            <p>But other types of noise can be distracting, irritating, or even stressful -- the hammering from the
                building site across the street, the stomping of the neighbors in the apartment upstairs, or the
                thumping bass from the party outside.
            </p>
        </div>
        <div class="px-3">
            <p><b>SOUNDeeD</b> is designed to help you ignore bothersome noise by playing custom ambient sounds to suit your
                environment.
            </p>
            <p>
                There are quite a few sounds for you to choose from: rain, birdsong, wind blowing, and so on. You can
                mix them together for the best experience. You can mix them together for the best experience. Moreover, when you sign
                up for an account here, you can keep your own playlists of your favorites because we know it's hard for
                hard-core people to find a playlist of many sounds mixed with each sound having a different volume is
                very difficult.
            </p>
            <p>
                If you need a watch to determine how long you need to focus, then the Podoromo is the best choice for
                you. Podoromo is integrated into the website allowing you to customize the countdown interval and notify
                you if the time is up. Of course, it helps you to manage your time better without having to look at your
                watch every time you are concentrating on work.
            </p>
            <p>
                If you are tired of looking at the background of the website, you can choose from different backgrounds
                from the website, including dynamic or static wallpapers. Don't worry about it, our web-integrated
                backgrounds have been carefully selected for your comfort.
            </p>
            <p>
                To increase your ability to focus on the sounds created by you, we recommend using earplugs. These tend
                to work well for some frequencies of sounds and less well for others. I would sometimes wear earplugs,
                then put my over-ear noise-canceling headphones on top playing ambient music and nature sounds. It’s
                amazing what the mind comes up with when you really, really need to sleep.
            </p>
            <div class="px-3">
                <p>
                    I hope <b>SOUNDeeD</b> is enjoyable and useful for you and we you have a relaxing day! From  <a href="https://facebook.com/nh4ttruong"><b style="color: yellow;">nh4ttruong</b></a> and <a href="https://www.facebook.com/gnudnaod"><b style="color: yellow;">dr00py</b></a> with love!
                </p>
            </div>
        </div>
    </div>
</div>

soundeed/main/templates/pages/background.html
<div id="background" class="element-sound d-none text-center">
    <div class="container" id="bg-container">
        <div class="row">
            {% for i in background %}
            <div class="col-6 col-md-3 my-4 element">
                <input type="radio" name="background" id="bg{{i.id}}" class="input-hidden"/>
                <label for="bg{{i.id}}">
                    <img id="img{{i.id}}" src="media/{{i.thumbnail}}" alt="{{i.background}}" class="thumbnail">
                </label>
                <h4>{{ i.title }}</h4>
            </div>
            {% endfor %}
        </div>
    </div>
    
    <button type="button" onclick="changeBackground()" class="btn-custom mx-auto border-none shadow-none justify-content-center">
        <i class="fas fa-check fa-2x text-black-50"></i>
    </button>
    
</div>

soundeed/main/templates/pages/error.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SOUNDeeD·404</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/error.css' %}" type="text/css">
    
</head>
<body>
    {% include "pages/head.html" %}
    <div id="main">
        <div class="fof">
            <h1 class="font-weight-bold">Oops, an error occurred!</h1>
        </div>
    </div>
</body>
</html>

soundeed/main/templates/pages/head.html
{% load static %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark bg-transparent w-100" style="z-index: 9999; position: fixed; top: 0;">
    <div class="container-fluid">
      <a class="navbar-brand font-weight-bolder" style="font-size: 30px;" href="/">SOUNDeeD</a>
      <button class="navbar-toggler ml-auto text-white border border-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        </ul>
        <ul class="navbar-nav mb-2 mb-lg-0">
            <li class="nav-item text-white">
              <a class="nav-link active pr-3" aria-current="page" href="#background" onclick="showBackground()" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show" >Background</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item text-white">
                <a id="mysound" class="nav-link active" aria-current="page" href="#playlist" onclick="showPlaylist()" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">Playlist</a>
            </li>
            <li class="nav-item text-white">
                <a class="nav-link active pr-3" aria-current="page" href="#about" onclick="showAbout()" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">About</a>
            </li>    
            <li class="btn-group">
                <div class="dropdown">
                    <a class="btn dropdown-toggle border-0 bg-transparent text-white font-weight-bold shadow-none pt-2 px-0" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false" style="color:white">
                      Welcome {{user}}!
                    </a>
                    <ul class="dropdown-menu bg-transparent border-0" aria-labelledby="dropdownMenuLink">
                      {% if user.is_superuser %}
                      <li><a class="dropdown-item bg-transparent text-white-50 px-1" href="/admin">Admin Gate</a></li>
                      {% else %}
                      <li><a class="dropdown-item bg-transparent text-white-50 px-1" href="/password_change">Change Password</a></li>
                      {% endif %}
                      <li><a class="dropdown-item bg-transparent text-white-50 px-1" href="/logout" >Sign Out</a></li>
                    </ul>
                  </div>
            </li>
          {% else %}
            <li class="nav-item text-white">
              <a class="nav-link active" aria-current="page" href="/login">Playlist</a>
            </li>
            <li class="nav-item text-white">
                <a class="nav-link active pr-3" aria-current="page" href="#about" onclick="showAbout()" data-bs-toggle="collapse" data-bs-target=".navbar-collapse.show">About</a>
            </li>   
            <li class="btn-group">
                <div class="dropdown">
                    <a class="btn dropdown-toggle border-0 bg-transparent text-white shadow-none pt-2 px-0" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                      Account
                    </a>
                    <ul class="dropdown-menu bg-transparent border-0" aria-labelledby="dropdownMenuLink">
                      <li><a class="dropdown-item bg-transparent text-white-50 px-1" href="/register">Register</a></li>
                      <li><a class="dropdown-item bg-transparent text-white-50 px-1" href="/login">Login</a></li>
                    </ul>
                  </div>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

{% endblock %}

soundeed/main/templates/pages/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="shortcut icon" type="image/svg+xml" href="{% static 'icon2.svg' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/home.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/sound.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/player.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/pomodoro.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/background.css' %}" type="text/css">
    {% block styles %}

    {% endblock %}
    <title>SOUNDeeD · Sound & Chill</title>
</head>

<body>
    <div class="bg">
        <img id="static" src="/static/img/default.png" alt="" class="img-bg">
        <video autoplay muted loop id="dynamic" class="vid-bg d-none"></video>
    </div>
    {% include "pages/head.html" %}
    <div id="home" class="homepage">
        <div class="container parallax-content">
            {% include "pages/sound.html" %}

            {% include "pages/background.html" %}

            {% if user.is_authenticated %}

            {% include "pages/playlist.html" %}

            {% endif %}

            {% include "pages/pomodoro.html" %}

            {% include "pages/about.html" %}

            <div class="col-12 col-md-12 col-lg-8 d-flex justify-content-center flex-column" id="welcome-text">
                <h1>Welcome to SOUNDeeD</h1>
            </div>
        </div>
    </div>
    <div id="player" class="player">
        {% include "pages/player.html" %}
    </div>

</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.16.1/TweenMax.min.js"></script>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/handle.js' %}"></script>
<script src="{% static 'js/player.js' %}"></script>
<script src="{% static 'js/pomodoro.js' %}"></script>

</html>

soundeed/main/templates/pages/player.html
{% load static %}

<div id="info" class="info">
    <span id="playlistTitle" class="sound-name">Test Name</span>
</div>
<div id="control-panel" class="control-panel">
    <div class="disc d-none d-md-block"></div>
    <div class="controls">
        <a href="#elements">
            <div id="soundelement" class="list" onclick="showSound()"></div>
        </a>
        <a href="#playsound">
            <div id="play" class="play" onclick="playSound()"></div>
        </a>
        <a href="#pomodoro">
            <div id="podomoroelement" class="pomodoro" onclick="showPodomoro()"></div>
        </a>
    </div>
</div>

soundeed/main/templates/pages/playlist.html
<div id="playlist" class="element-sound d-none text-center overflow-auto position-relative">
    <div class="container" id="playlist-container">
        <div class="row">

            {% for pl in user.playlist_set.all %}

            <div class="col-6 col-md-4 my-4 element">
                <div class="nameList" style="font-size: 20px;">{{pl}}</div>
                <div class="config d-inline-flex justify-content-center">
                    <div class="edit pt-4 pb-3">
                        <a class="btn-playlist" id="play{{pl.id}}" onclick="handlePl('{{pl.playlist}}', '{{pl.id}}', '{{pl.title}}')">
                            <i id="control{{pl.id}}" class="fas fa-play fa-2x controlSound"></i>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div id="setPlaylist" class="container d-none">
        <form method="post" action="#elements">
            {% csrf_token %}
             <div class="mt-5">
                <h4>Playlist Name</h4>
                <input id="playlistName" name="new" type="text" class="w-50 my-5"
                    style="background-color:rgba(255, 255, 255, 0.795); line-height: 35px;">
                <input class="d-none" name="addPlayList" id="playlist_here" type="text">
            </div>       
    
            <div class="row d-inline-flex mb-4">
                <div class="col-6">
                    <button type="submit" onclick="retPlayList()" class="playlist-btn fas fa-plus fa-2x text-black-50">
                    </button>
                </div>
                <div class="col-6">
                    <button type="button" name="dis" id="cancelBtn" class="playlist-btn fas fa-times fa-2x text-black-50"
                        onclick="cancel()">
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

soundeed/main/templates/pages/podomoro.html
<div id="podomoro" class="podomoro-con d-none">
  <div class="container no-select">
    <a href="#podomoro" class="text-decoration-none">
      <h2 class="text-center mx-auto py-4">PODOMORO</h2>
    </a>
    <div class="minutes text-center">
      <div class="row-cols-3 d-flex py-3">
        <div id="periodSS" class="row-cols-2 my-auto">
          <span class="lv1">PERIOD</span>
          <span class="lv1">
            <div class="row-cols-3 d-flex">
              <a id="s-down" class="updown"><i class="fas fa-minus"></i></a>
              <span id="period" style="font-size: 30px;">1</span>
              <a id="s-up" class="updown"><i class="fas fa-plus"></i></a>
            </div>
          </span>
        </div>
        <!--Timer icon-->
        <div class='timer my-auto py-3'>
          <div class="timer-backboard">
            <i class="fa fa-hourglass" aria-hidden="true"></i>
          </div>
          <div class="timer-visible">
            <i class="fa fa-hourglass" aria-hidden="true"></i>
          </div>
        </div>
        <div id="breakSS" class="row-cols-2 my-auto">
          <span class="lv1">BREAK</span>
          <span class="lv1">
            <div class="row-cols-3 d-flex">
              <a id="b-down" class="updown"><i class="fas fa-minus"></i></a>
              <span id="break" style="font-size: 30px;">1</span>
              <a id="b-up" class="updown"><i class="fas fa-plus"></i></a>
            </div>
          </span>
        </div>
      </div>
    </div>


    <div class="time-left text-center mx-auto my-auto pt-1 pb-2" style="font-weight: bolder; font-size: 3rem;"><span
        id="mins">1</span>m <span id="secs">0</span>s</div>

    <div class="controls text-center pt-3 pb-4">
      <a id="toggle" class="btn btn-noselect">Start</a>
      <!-- do warning pause-->
      <a id="reset" class="btn btn-noselect">Reset</a>
    </div>
  </div>
</div>

soundeed/main/templates/pages/pomodoro.html
<div id="pomodoro" class="pomodoro-con d-none">
  <div class="container no-select">
    <a href="#pomodoro" class="text-decoration-none">
      <h2 class="text-center mx-auto py-4">POMODORO</h2>
    </a>
    <div class="minutes text-center">
      <div class="row-cols-3 d-flex py-3">
        <div id="periodSS" class="row-cols-2 my-auto">
          <span class="lv1">PERIOD</span>
          <div class="lv1">
            <div class="row-cols-3 d-flex">
              <a id="s-down" class="updown"><i class="fas fa-minus"></i></a>
              <span id="period" style="font-size: 30px;">1</span>
              <a id="s-up" class="updown"><i class="fas fa-plus"></i></a>
            </div>
          </div>
        </div>
        <!--Timer icon-->
        <div class='timer my-auto py-3'>
          <div class="timer-backboard">
            <i class="fa fa-hourglass" aria-hidden="true"></i>
          </div>
          <div class="timer-visible">
            <i class="fa fa-hourglass" aria-hidden="true"></i>
          </div>
        </div>
        <div id="breakSS" class="row-cols-2 my-auto">
          <span class="lv1">BREAK</span>
          <div class="lv1">
            <div class="row-cols-3 d-flex">
              <a id="b-down" class="updown"><i class="fas fa-minus"></i></a>
              <span id="break" style="font-size: 30px;">1</span>
              <a id="b-up" class="updown"><i class="fas fa-plus"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="time-left text-center mx-auto my-auto pt-1 pb-2" style="font-weight: bolder; font-size: 3rem;"><span
        id="mins">1</span>m <span id="secs">0</span>s</div>

    <div class="controls text-center pt-3 pb-4">
      <a id="toggle" class="btn btn-noselect">Start</a>
      <!-- do warning pause-->
      <a id="reset" class="btn btn-noselect">Reset</a>
    </div>
  </div>
</div>

soundeed/main/templates/pages/sound.html
{% load static %}
<div id="elements" class="element-sound d-none text-center overflow-auto position-relative">
    <div class="container px-0" id="sound-container">
        <div class="row" id="con-row">

            {% for i in sound %}

            <div class="col-6 col-md-3 my-4 element">
                <div class="icon" style="font-size: 5rem;">
                    <button onclick="playStop(Sound{{i.id}})" type="button" class="icon-button">
                        {% if i.icon|length == 0 %}
                        <img class="avatar" src="/media/{{i.avatar}}" alt="{{i.title}} icon"/>
                        {% else %}
                        <i class="avatar {{i.icon}}" id="IconSound{{i.id}}"></i>
                        {% endif %}
                    </button>
                    <audio id="Sound{{i.id}}" class="sounds" loop>
                        <source src="media/{{i.audio}}" type="audio/mp3">
                    </audio>
                </div>
                <div class="icon-body">
                    <h3>{{ i.title }}</h3>
                    <div class="slidercontainer">
                        <input type="range" min="1" max="100" value="40" oninput="setVolume(Sound{{i.id}}, this.value)" class="slider" id="SliderSound{{i.id}}">
                    </div>
                </div>
            </div>

            {% endfor %}

        </div>
    </div>
    <div class="row-cols-2">
        {% if user.is_authenticated %}
        <button id="btnSetPlaylist" type="submit" onclick="setPlaylist()" class="btn-custom mx-auto px-2 border-none shadow-none justify-content-center">
            <i class="fas fa-plus fa-2x text-black-50"></i>
        </button>
        {% else %}
        <button id="btnSetPlaylist" type="button" onclick="location.href='/login'" class="btn-custom mx-auto px-2 border-none shadow-none justify-content-center">
            <i class="fas fa-plus fa-2x text-black-50"></i>
        </button>
        {% endif %}
        <button id="btnRandom" type="button" onclick="randomMix()" class="btn-custom mx-auto px-2 border-none shadow-none justify-content-center">
            <i class="fas fa-random fa-2x text-black-50"></i>
        </button>
    </div>
</div>